var memesPackage = {
	"name": "Memes",
	"image": "http://i.imgur.com/MWIM2QW.png",
	"emoticons": {
			
		

		// Memes
		"meabuela"					:"http://i.imgur.com/bYLbZ.png",
		"meallthe"					:"http://i.imgur.com/NQLgABe.png",
		"meamazed"					:"http://i.imgur.com/3qpxZ.jpg",
		"meareyoukiddingme"			:"http://i.imgur.com/THHMk.gif",
		"meareyouserious"			:"http://i.imgur.com/pyfN1.jpg",
		"meascoyaoming"				:"http://i.imgur.com/ka9CG.png",
		"meawyeah"					:"http://i.imgur.com/vwfs8.png",
		"mebailoteo"				:"http://i.imgur.com/J98nL7s.gif",
		"mebetterthanexpected"		:"http://i.imgur.com/ABt6Z.gif",
		"mecerealguy"				:"http://i.imgur.com/AUEmq.gif",
		"mechallengeaccepted"		:"http://i.imgur.com/aVnrn.gif",
		"mechicamorena"				:"http://i.imgur.com/JYQDw.jpg",
		"mechicaokay"				:"http://i.imgur.com/x5Qjz.png",
		"mechicaokaymorena"			:"http://i.imgur.com/Kh7Qc.png",
		"mechicaomgrun"				:"http://i.imgur.com/DhAQW.jpg",
		"mechicapokerface"			:"http://i.imgur.com/6G47p.png",
		"mechicarubia"				:"http://i.imgur.com/1yoKW.jpg",
		"mechicasonriendo"			:"http://i.imgur.com/b8psS.png",
		"mecomputerguy"				:"http://i.imgur.com/hGXjF.jpg",
		"mefapfapfap"				:"http://i.imgur.com/pjKqG.png",
		"mefliptable"				:"http://i.imgur.com/yCXAh26.png",
		"meforeveralone"			:"http://i.imgur.com/JdZMs.jpg",
		"mefreddiemercury"			:"http://i.imgur.com/QXzcs.png",
		"mefry"						:"http://i.imgur.com/9QT6f.png",
		"mefuckyeah"				:"http://i.imgur.com/G0DL5.gif",
		"mefuuu"					:"http://i.imgur.com/0HBhP.gif",
		"megenius"					:"http://i.imgur.com/Yzu6CU9.png",
		"megordogranudo"			:"http://i.imgur.com/JXUlp.jpg",
		"mehappyforeveralone"		:"http://i.imgur.com/ejL9Z.png",
		"meifyouknow"				:"http://i.imgur.com/9PxQoCa.png",
		"meinfinitodesprecio"		:"http://i.imgur.com/tNo35.jpg",
		"meitsfree"					:"http://i.imgur.com/dKlOl.jpg",
		"meitssomething"			:"http://i.imgur.com/6iyyu.gif",
		"mejackiechan"				:"http://i.imgur.com/L6Tjr.png",
		"mejumpcat"					:"http://i.imgur.com/BwNzqHX.gif",
		"melikea5yearsold"			:"http://i.imgur.com/Z4OQe.jpg",
		"melikeaninja"				:"http://i.imgur.com/dMA8S.gif",
		"melikeasir"				:"http://i.imgur.com/a6btr.gif",
		"melol"						:"http://i.imgur.com/9A2GC.gif",
		"memegusta"					:"http://i.imgur.com/w9XZd.gif",
		"me1menti"			 		:"http://i.imgur.com/ZMgbd.png",
		"mementira"					:"http://i.imgur.com/7rYJW.gif",
		"memiraaqui"				:"http://i.imgur.com/1lspE.gif",
		"memiradafija"				:"http://i.imgur.com/uyHOM.jpg",
		"memotherofgod"				:"http://i.imgur.com/LqCyL.jpg",
		"meNO"						:"http://i.imgur.com/hR726.jpg",
		"menomedigas"				:"http://i.imgur.com/t8SA0.jpg",
		"menotbad"					:"http://i.imgur.com/CjpOh.jpg",
		"menothingtodohere"			:"http://i.imgur.com/6EdnK.gif",
		"meohgodwhy"				:"http://i.imgur.com/AXelp3y.png",
		"meokay"					:"http://i.imgur.com/mkCw3.gif",
		"meolakase"					:"http://i.imgur.com/MqJMk.gif",
		"me1olakase"				:"http://i.imgur.com/TGuok.gif",
		"meomgrun"					:"http://i.imgur.com/vQyNLuz.png",
		"meorly"					:"http://i.imgur.com/6NqRv.gif",
		"mepatbateman"				:"http://i.imgur.com/LUwdr.gif",
		"mepensativo"				:"http://i.imgur.com/eZxzQ.png",
		"mepeter"					:"http://i.imgur.com/0DNzs.png",
		"mepokerface"				:"http://i.imgur.com/DQJIa.jpg",
		"mepukerainbows"			:"http://i.imgur.com/LM753.gif",
		"meraisins"					:"http://i.imgur.com/vq7X9.gif",
		"me1raisins"				:"http://i.imgur.com/p2idF.gif",
		"meretarded"				:"http://i.imgur.com/QQ5rG.png",
		"mesexykardynal"			:"http://i.imgur.com/SIDAOZO.gif",
		"mesiclaro"					:"http://i.imgur.com/V9aN2.png",
		"mesoclose"					:"http://i.imgur.com/rcNzH.jpg",
		"mesuccess"					:"http://i.imgur.com/LQE3lkv.png",
		"mesurprise"				:"http://i.imgur.com/paM6bqR.gif",
		"mesuspicious"				:"http://i.imgur.com/BXvcxQt.png",
		"metakemymoney"				:"http://i.imgur.com/lFjp6Y6.png",
		"methatssuspicious"			:"http://i.imgur.com/8WFcG.gif",
		"metheobserver"				:"http://i.imgur.com/npiSq.jpg",
		"metrolldad"				:"http://i.imgur.com/mzmft.png",
		"metrollface"				:"http://i.imgur.com/aukR5.gif",
		"metruestory"				:"http://i.imgur.com/6CgSL.jpg",
		"mewatchingyou"				:"http://i.imgur.com/kLonS.gif",
		"mewhaaat"					:"http://i.imgur.com/NzBR76p.png",
		"mewhathaveidone"			:"http://i.imgur.com/b3Llq.gif",
		"mewhynot"					:"http://i.imgur.com/U85Yw.gif",
		"mewicked"					:"http://i.imgur.com/liWndcs.png",
		"meyaoming"					:"http://i.imgur.com/AlFpq.gif",
		"meyuno"					:"http://i.imgur.com/8EVMs.gif"
	}
}


if (typeof exports !== 'undefined') exports.memesPackage = memesPackage;
