var robotPackage = {
	"name": "Robot",
	"image": "http://i.imgur.com/KcXCqU8.png",
	"emoticons": {
		"roabrigado"			:"http://i.imgur.com/gIUFheQ.gif",
		"roajam"				:"http://i.imgur.com/8IYriQn.gif",
		"roamor"				:"http://i.imgur.com/jPK0rzE.gif",
		"robaba"				:"http://i.imgur.com/IZFD5RP.gif",
		"robailar"				:"http://i.imgur.com/6bCZJsw.gif",
		"ro1bailar"				:"http://i.imgur.com/2D5VguG.gif",
		"robajon"				:"http://i.imgur.com/QfZPSUP.gif",
		"robajon"				:"http://i.imgur.com/tBMovkD.gif",
		"robye"					:"http://i.imgur.com/Hn8YD9u.gif",
		"rocagoen"				:"http://i.imgur.com/jpvV8nw.gif",
		"rocharlatan"			:"http://i.imgur.com/xr7TJq3.gif",
		"rocomba"				:"http://i.imgur.com/qihOVhK.gif",
		"rocomo"				:"http://i.imgur.com/ZEzrRIk.gif",
		"rodibujar"				:"http://i.imgur.com/1GgPLBH.gif",
		"rodown"				:"http://i.imgur.com/fpyuyvd.gif",
		"roein"					:"http://i.imgur.com/U5hjB00.gif",
		"ro1ein"				:"http://i.imgur.com/2JqO21B.gif",
		"ro2ein"				:"http://i.imgur.com/c0ptfug.gif",
		"roequilibrio"			:"http://i.imgur.com/PbCvKbz.gif",
		"roguitarra"			:"http://i.imgur.com/nX3Njgz.gif",
		"rogym"					:"http://i.imgur.com/GsCtWA5.gif",
		"rohelado"				:"http://i.imgur.com/waXXVks.gif",
		"rohulahoop"			:"http://i.imgur.com/FvoK2VY.gif",
		"rojoo"					:"http://i.imgur.com/Rw63ZeP.gif",
		"rojope"				:"http://i.imgur.com/lfm2pSZ.gif",
		"rojoyaamor"			:"http://i.imgur.com/cjwai8J.gif",
		"roju"					:"http://i.imgur.com/0JJ0tPa.gif",
		"roko"					:"http://i.imgur.com/sJKM5a0.gif",
		"rolatework"			:"http://i.imgur.com/wXZf1Nq.gif",
		"roleer"				:"http://i.imgur.com/YDd0gwa.gif",
		"romareo"				:"http://i.imgur.com/spnSccq.gif",
		"romiedo"				:"http://i.imgur.com/5TKggny.gif",
		"ro1miedo"				:"http://i.imgur.com/lcnVNM4.gif",
		"romimir"				:"http://i.imgur.com/bj2VToe.gif",
		"rommm"					:"http://i.imgur.com/XC8MsKV.gif",
		"romudo"				:"http://i.imgur.com/HwQzwVz.gif",
		"ronoel"				:"http://i.imgur.com/lxbsACI.gif",
		"ronomepegues"			:"http://i.imgur.com/T3xRyj4.gif",
		"roomg"					:"http://i.imgur.com/pXImHFW.gif",
		"roooohh"				:"http://i.imgur.com/2VUECiT.gif",
		"roparaguas"			:"http://i.imgur.com/JFPfYu7.gif",
		"ropataleta"			:"http://i.imgur.com/AasbaOn.gif",
		"ropica"				:"http://i.imgur.com/PijGegl.gif",
		"ropoto"				:"http://i.imgur.com/6FodGd2.gif",
		"roprocigarro"			:"http://i.imgur.com/AgArBWc.gif",
		"ro1procigarro"			:"http://i.imgur.com/nYpUQNN.gif",
		"roregalo"				:"http://i.imgur.com/4RKq94W.gif",
		"roregaña"				:"http://i.imgur.com/YKygwFb.gif",
		"rosilbar"				:"http://i.imgur.com/ZN6Uwd6.gif",
		"rospray"				:"http://i.imgur.com/3VmV8iY.gif",
		"roterico"				:"http://i.imgur.com/FnB0Tsu.gif",
		"rotimido"				:"http://i.imgur.com/wMVnH3I.gif",
		"rotosolo"				:"http://i.imgur.com/hNsMsZQ.gif",
		"roufff"				:"http://i.imgur.com/OMOi6fA.gif",
		"rouooo"				:"http://i.imgur.com/i152HLJ.gif",
		"roXD"					:"http://i.imgur.com/Sjay2Dn.gif"
	}
}			


if (typeof exports !== 'undefined') exports.robotPackage = robotPackage;
